### ISSUE TITLE
[Feature suggestion] In-built help and documentation for glimmer specific code, via glimmer-cs-gladiator

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-cs-gladiator#17]
Hey there Andy,

I recently adapted kojix2 rubio example, as I did not have a glimmer-app yet in one of my gems.

While looking at kojix2' code - he is writing in a style that is very concise and short, but also shy
of comments - I found various Glimmer-specific methods, which were unknown to me at the
time.

For instance:

    Glimmer::LibUI.timer()
    Glimmer::LibUI.queue_main()
    Glimmer::DataBinding::Observer::Proc.new

And so forth. To some extent I understand these, to a limited way, as I saw similar code in
ruby-gtk years ago; so the timer is probably just a protected call to counting how time
passes by (in "ticks"; I think GLib in gtk does something similar), queue_main I assume
is to run via a protected thread (again I am just making assumptions) and the Observer
thingy is to update the table entries shown dynamically - or at the least I am guessing 
it. I have not studied the code in detail.

Now I can search for these examples and it would not be too difficult to find it, but then
I was also wondering ... "what if there is an in-built way to look up ANY Glimmer API?"

Naturally this then led me to propose this here for the glimmer-editor, as this may
make the most sense (e. g. we operate all within the glimmer-editor, so also in-built
help and documentation should ideally be available; and perhaps you already do so,
anyway). I guess in the simplest way, implementation wise, two things I can think 
about:

1) the more elegant way would be to have some dedicated small widget where, upon
a selection of a glimmer-API, such as the three ones mentioned above, it is shown
what this does, aka "this API conjures dragons" and "that API makes sure the application
does not crash unexpectedly, but gracefully". You probably already have all that
documentation stored in glimmer, so this should only be a matter of displaying that
to the end user (or rather dev, who is using the glimmer editor, or any other glimmer
specific widget where such help can be shown, such as the www-implementations).

2) an even much simpler way would be to just have an input text field where we can
type (or copy/paste) into, and then a small button we can click, which then shows
whether this API is known or not. This one may not be as elegant as the above,
but probably much easier and faster to implement. And if need be it could be improved
anyway at a later time.

The rationale for this suggestion is to provide a "stay within the glimmer world" 
approach, e. g. for people to operate within glimmer as much as possible, without
"needing" to leave it. Of course google search and what not may all be more 
convenient, but I think there is merit to the idea that we can solve all glimmer-related
issues from WITHIN glimmer-code, like a whole glimmer environment.

I have a few more loose ideas I am certain you are eager to listen to, for the amount
of work when having limited time :D - ultimately these are just some semi-random 
ideas. One I may propose, but for glimmer instead, would be for "glimmer components",
e. g. to describe glimmer-specific widgets and ready-made solutions for such widgets
in an agnostic format, in addition to the DSL (or non-DSL) that is provided/offered. But
that would be for another suggestion - end of the year is often lazy time here so not
sure how canadians go about it, but I can already feel the cold factor kicking in here,
trees dropping their leaves and it's quite cold already in central europe. Anyway I end
that here now - as always please feel free to proceed in any way shape or form with
suggestions made. glimmering into the new year soon. \o/

**Comment by AndyObtiva** [comment]
I think with the time you put into writing your very long requests, you could implement them instead and submit a pull request. For example, if some documentation is missing, add it in a pull request. I hope you know how to use pull requests in GitHub. If you don't, you have bigger problems to worry about than your request. Also, if you think of a tool that could simplify usage of Glimmer API, then build it, and share with me a new project link or pull request out of the good will of your heart like any true open source developer would do. I am closing this.
