### ISSUE TITLE
Low priority suggestion: a short video for glimmer-cs-gladiator (perhaps around the range of ~5 minutes or something, just an intro and overview)

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-cs-gladiator#7]
Hey there Andy,

The README currently has this comment:

"Otherwise, I have been happily using Gladiator to develop all my projects since May of 2020"

I think it may be interesting for some users or visitors to perhaps showcase a somewhat short video, just as an example how you may use glimmer-cs-gladiator specifically. This does not have to be long or too fancy or complicated; perhaps around 5 minutes or so, give or take, I think should suffice, with just some key examples shown here. For instance, writing a hello-world via glimmer-cs-gladiator for some examples in the glimmer-suite, including a few examples forthat, such as "go to line", remove text, replace text, change font size or something like that. Perhaps just a few entries that you mention in the current features list of glimmer-cs-gladiator, and meant as just a general introduction. It could also give users a somewhat better idea to just use glimmer-cs-gladiator as an editor, if you work with it since the last ~2 years. (I tried to write a ruby-gtk3-editor, but it is nowhere near complete, missing tons of features and I am working on it very irregularly, so this would also be interesting to see how useful glimmer-cs-gladiator could be from that perspective.)

This video could then linked in directly from the README here,or if you deem it better as part of a playlist on youtube. (Though I guess a simple directl URL is easier, unless you want to specifically integrate the video as part of the glimmer-dsl-swt or something, such as a specific featured app.)

It could be considered as a slight extension towards introducing the glimmer suite, aka "use glimmer, from within glimmer, to write glimmer-specific code/applications".

**Comment by AndyObtiva** [comment]
The video you are asking for is already made and is included in the README already as an animated GIF file. You just have to scroll down a bit to [find it under Features](https://github.com/AndyObtiva/glimmer-cs-gladiator#features). I even launch a Glimmer app from the editor and it is Hello, World! just as you suggested.

I am including the video demo again here for your convenience:
![gladiator demo](https://github.com/AndyObtiva/glimmer-cs-gladiator/raw/master/images/glimmer-gladiator.gif)
